import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";
import { generate } from "orval";
import { format, resolveConfig } from "prettier";

const scriptsDirectory = path.dirname(fileURLToPath(import.meta.url));

export const repositoryRoot = path.resolve(scriptsDirectory, "../..");
export const contractDirectory = path.join(
  repositoryRoot,
  "src/contracts/lamara-api",
);
export const snapshotPath = path.join(contractDirectory, "openapi.yaml");
export const generatedPath = path.join(contractDirectory, "generated.ts");
export const runtimeGeneratedPath = path.join(
  contractDirectory,
  "runtime.generated.ts",
);
export const provenancePath = path.join(contractDirectory, "provenance.json");

const generatedHeader = `/**
 * This file was generated by openapi-typescript.
 * Do not edit it directly. Run \`pnpm contracts:generate\` instead.
 */

`;

export function parseSyncArguments(arguments_) {
  let source;

  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];

    if (argument === "--") {
      continue;
    }

    if (argument === "--source") {
      const value = arguments_[index + 1];
      if (!value || value.startsWith("--")) {
        throw new Error("--source requires a file path.");
      }
      if (source) {
        throw new Error("--source may only be provided once.");
      }
      source = value;
      index += 1;
      continue;
    }

    if (argument.startsWith("--source=")) {
      const value = argument.slice("--source=".length);
      if (!value) {
        throw new Error("--source requires a file path.");
      }
      if (source) {
        throw new Error("--source may only be provided once.");
      }
      source = value;
      continue;
    }

    throw new Error(`Unknown argument: ${argument}`);
  }

  if (!source) {
    throw new Error(
      "Missing --source. Example: pnpm contracts:sync -- --source /path/to/openapi.yaml",
    );
  }

  return { sourcePath: path.resolve(source) };
}

export function assertOpenApiSnapshot(contents) {
  const source = contents.toString("utf8");

  if (!/^openapi:\s+3\.\d+\.\d+\s*$/m.test(source)) {
    throw new Error("Source is not an OpenAPI 3.x document.");
  }

  if (!/^paths:\s*$/m.test(source)) {
    throw new Error("OpenAPI source does not declare paths.");
  }
}

export function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

export function hasContractDrift(committed, generated) {
  return !committed.equals(generated);
}

export async function readSourceProvenance(sourceFilePath, contents) {
  const sourceDirectory = path.dirname(sourceFilePath);
  const gitRoot = runGit(sourceDirectory, ["rev-parse", "--show-toplevel"]);
  const sourceRelativePath = toPosix(path.relative(gitRoot, sourceFilePath));

  runGit(gitRoot, ["ls-files", "--error-unmatch", "--", sourceRelativePath]);

  const sourceStatus = runGit(
    gitRoot,
    ["status", "--porcelain", "--", sourceRelativePath],
    { allowEmpty: true },
  );
  if (sourceStatus) {
    throw new Error(
      `OpenAPI source has uncommitted changes: ${sourceRelativePath}`,
    );
  }

  const repository =
    runGit(gitRoot, ["config", "--get", "remote.origin.url"], {
      allowEmpty: true,
    }) || path.basename(gitRoot);

  return {
    schemaVersion: 1,
    sourceRepository: repository,
    sourceCommit: runGit(gitRoot, ["rev-parse", "HEAD"]),
    sourcePath: sourceRelativePath,
    sha256: sha256(contents),
  };
}

export async function generateContractSource(inputPath = snapshotPath) {
  const ast = await openapiTS(pathToFileURL(inputPath), {
    alphabetize: true,
    exportType: true,
    immutable: true,
  });
  const unformatted = `${generatedHeader}${astToString(ast)}`;
  const prettierConfig = (await resolveConfig(generatedPath)) ?? {};

  return format(unformatted, {
    ...prettierConfig,
    filepath: generatedPath,
  });
}

export async function generateRuntimeContractSource(inputPath = snapshotPath) {
  const temporaryDirectory = await fs.mkdtemp(
    path.join(os.tmpdir(), "lamara-runtime-contract-"),
  );
  const temporaryOutputPath = path.join(
    temporaryDirectory,
    "runtime.generated.ts",
  );

  try {
    await generate(
      {
        input: {
          target: inputPath,
        },
        output: {
          client: "zod",
          mode: "single",
          target: temporaryOutputPath,
          override: {
            zod: {
              generate: {
                body: false,
                header: false,
                param: false,
                query: false,
                response: true,
              },
              generateReusableSchemas: true,
              variant: "classic",
              version: 4,
            },
          },
        },
      },
      repositoryRoot,
      {
        failOnWarnings: true,
      },
    );

    const source = await fs.readFile(temporaryOutputPath, "utf8");
    const prettierConfig = (await resolveConfig(runtimeGeneratedPath)) ?? {};

    return format(source, {
      ...prettierConfig,
      filepath: runtimeGeneratedPath,
    });
  } finally {
    await fs.rm(temporaryDirectory, { recursive: true, force: true });
  }
}

export async function writeFileAtomic(targetPath, contents) {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  const temporaryPath = path.join(
    path.dirname(targetPath),
    `.${path.basename(targetPath)}.${process.pid}.${randomUUID()}.tmp`,
  );

  try {
    await fs.writeFile(temporaryPath, contents, { flag: "wx" });
    await fs.rename(temporaryPath, targetPath);
  } finally {
    await fs.rm(temporaryPath, { force: true });
  }
}

function runGit(cwd, arguments_, options = {}) {
  try {
    return execFileSync("git", arguments_, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    }).trim();
  } catch (error) {
    if (
      options.allowEmpty &&
      typeof error === "object" &&
      error !== null &&
      "status" in error &&
      error.status === 1
    ) {
      return "";
    }

    const stderr =
      typeof error === "object" && error !== null && "stderr" in error
        ? error.stderr
        : "";
    const detail = Buffer.isBuffer(stderr)
      ? stderr.toString("utf8").trim()
      : typeof stderr === "string"
        ? stderr.trim()
        : "";
    throw new Error(
      `Git command failed: git ${arguments_.join(" ")}${detail ? `\n${detail}` : ""}`,
      { cause: error },
    );
  }
}

function toPosix(value) {
  return value.split(path.sep).join("/");
}
