const ALLOWED_SCOPES = [
  "api",
  "app",
  "auth",
  "build",
  "ci",
  "config",
  "contracts",
  "deps",
  "docs",
  "downloads",
  "e2e",
  "harness",
  "layout",
  "marketing",
  "privacy",
  "release",
  "seo",
  "sources",
  "test",
  "ui",
];

module.exports = {
  extends: ["@commitlint/config-conventional"],
  ignores: [
    (message) => message.startsWith("Merge ") || message.startsWith("Revert "),
  ],
  rules: {
    "body-max-line-length": [0],
    "footer-max-line-length": [0],
    "header-max-length": [2, "always", 100],
    "scope-enum": [2, "always", ALLOWED_SCOPES],
    "scope-empty": [2, "never"],
    "subject-case": [0],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
  },
};
