/**
 * This file was generated by openapi-typescript.
 * Do not edit it directly. Run `pnpm contracts:generate` instead.
 */

export type paths = {
  readonly "/.well-known/jwks.json": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * JWKS
     * @description Publishes public keys used to verify access tokens.
     */
    readonly get: operations["auth.jwks.get"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/health": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Liveness check
     * @description Indicates whether the process is alive.
     */
    readonly get: operations["health.get"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/ready": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Readiness check
     * @description Indicates whether the service is ready to receive traffic.
     */
    readonly get: operations["ready.get"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/admin/audit/user-account-deletions": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * List user account deletion events
     * @description Lists account deletion audit events (request/cancel/finalization). ID-only; filter by traceId to locate the originating request/job.
     */
    readonly get: operations["admin.audit.userAccountDeletions.list"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/admin/audit/user-role-changes": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * List user role changes
     * @description Lists role change audit events. Filter by traceId to locate the exact change request.
     */
    readonly get: operations["admin.audit.userRoleChanges.list"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/admin/users": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * List users
     * @description Admin-only user listing with cursor pagination, sorting, filtering, and search.
     */
    readonly get: operations["admin.users.list"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/admin/users/{userId}/role": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    /**
     * Set user role
     * @description Sets the user role. For /v1/admin/* endpoints, RBAC roles are hydrated from the database on every request (promotion/demotion takes effect immediately).
     */
    readonly patch: operations["admin.users.role.patch"];
    readonly trace?: never;
  };
  readonly "/v1/admin/users/{userId}/status": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    /**
     * Set user status
     * @description Sets the user status (ACTIVE/SUSPENDED). Suspended users cannot refresh tokens and are blocked from /v1/admin/* endpoints immediately.
     */
    readonly patch: operations["admin.users.status.patch"];
    readonly trace?: never;
  };
  readonly "/v1/admin/whoami": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Get current principal (admin)
     * @description Returns the authenticated principal. For /v1/admin/* endpoints, roles are hydrated from the database to ensure immediate demotion/promotion.
     */
    readonly get: operations["admin.whoami.get"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/email/verification/resend": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Resend verification email (current user)
     * @description Enqueues a new verification email for the authenticated user (rate limited).
     */
    readonly post: operations["auth.email.verification.resend"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/email/verify": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Verify email
     * @description Verifies a user email using a token sent via email.
     */
    readonly post: operations["auth.email.verify"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Logout
     * @description Revokes the session associated with the provided refresh token.
     */
    readonly post: operations["auth.logout"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/oidc/connect": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Connect OIDC identity (current user)
     * @description Links an OIDC identity (e.g., Google) to the authenticated user. If the OIDC email matches the user email, the user email is marked verified.
     */
    readonly post: operations["auth.oidc.connect"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/oidc/exchange": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Exchange OIDC id_token
     * @description Verifies an OIDC id_token (e.g., Google) and issues first-party access + refresh tokens. Does not auto-link to an existing password account purely by email.
     */
    readonly post: operations["auth.oidc.exchange"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/password/change": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Change password (current user)
     * @description Changes the authenticated user password. Revokes other sessions (and their refresh tokens) but keeps the current session active.
     */
    readonly post: operations["auth.password.change"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/password/login": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Login (password)
     * @description Authenticates a user and issues first-party access + refresh tokens.
     */
    readonly post: operations["auth.password.login"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/password/register": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Register (password)
     * @description Creates a user and immediately issues first-party access + refresh tokens.
     */
    readonly post: operations["auth.password.register"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/password/reset/confirm": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Confirm password reset
     * @description Resets the user password using a one-time token and revokes all sessions.
     */
    readonly post: operations["auth.password.reset.confirm"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/password/reset/request": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Request password reset
     * @description Enqueues a password reset email for an existing user. Returns 204 even if the email is unknown to avoid account enumeration.
     */
    readonly post: operations["auth.password.reset.request"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/auth/refresh": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Refresh tokens
     * @description Rotates the refresh token and returns a new access + refresh token.
     */
    readonly post: operations["auth.refresh"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Get current user
     * @description Returns the authenticated user profile.
     */
    readonly get: operations["users.me.get"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    /**
     * Update current user profile
     * @description Partially updates the authenticated user profile. Omitted fields are unchanged; null clears a field.
     */
    readonly patch: operations["users.me.patch"];
    readonly trace?: never;
  };
  readonly "/v1/me/account-deletion/cancel": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Cancel account deletion
     * @description Cancels a previously scheduled account deletion request.
     */
    readonly post: operations["users.me.accountDeletion.cancel"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/account-deletion/request": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Request account deletion (30-day grace)
     * @description Schedules account deletion 30 days in the future. The account remains usable during the grace period and the request can be canceled. After the grace period, the account is de-identified (PII erased) and the email becomes reusable.
     */
    readonly post: operations["users.me.accountDeletion.request"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/profile-image": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    /**
     * Clear current profile image
     * @description Detaches the current profile image (if any) and marks the stored file deleted. Object storage deletion is best-effort.
     */
    readonly delete: operations["users.me.profileImage.clear"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/profile-image/complete": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Finalize a profile image upload
     * @description Verifies the uploaded object and attaches it to the current user profile.
     */
    readonly post: operations["users.me.profileImage.complete"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/profile-image/upload": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Create a profile image upload plan (presigned URL)
     * @description Creates an upload record and returns a short-lived presigned URL for direct upload to object storage.
     */
    readonly post: operations["users.me.profileImage.upload"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/profile-image/url": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * Get current profile image URL
     * @description Returns a short-lived presigned URL for rendering the current profile image. Returns 204 when no profile image is set.
     */
    readonly get: operations["users.me.profileImage.url"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/push-token": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    /**
     * Register/update push token (current session)
     * @description Stores the FCM registration token for the current session. Idempotent; replaces any existing token for the session.
     */
    readonly put: operations["users.me.pushToken.upsert"];
    readonly post?: never;
    /**
     * Revoke push token (current session)
     * @description Clears the stored push token for the current session. Idempotent.
     */
    readonly delete: operations["users.me.pushToken.revoke"];
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/sessions": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /**
     * List current user sessions
     * @description Lists all sessions (active, revoked, expired) for the authenticated user. Revoked sessions have refresh tokens revoked; access tokens remain valid until expiry.
     */
    readonly get: operations["users.me.sessions.list"];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly "/v1/me/sessions/{sessionId}/revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /**
     * Revoke a session (current user)
     * @description Revokes the given session and its refresh tokens. Idempotent.
     */
    readonly post: operations["users.me.sessions.revoke"];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    readonly AccountDeletionDto: {
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly requestedAt: string;
      /**
       * Format: date-time
       * @example 2026-02-09T12:34:56.789Z
       */
      readonly scheduledFor: string;
    };
    readonly AdminUserAccountDeletionAuditDto: {
      /**
       * @example REQUESTED
       * @enum {string}
       */
      readonly action:
        "REQUESTED" | "CANCELED" | "FINALIZED" | "FINALIZE_BLOCKED_LAST_ADMIN";
      /** @example c1b6c1f7-5b2f-4e53-b33b-5af7f63a8c40 */
      readonly actorSessionId: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly actorUserId: string;
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly createdAt: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
      /** @example 9d8c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly targetUserId: string;
      /**
       * @description Equals X-Request-Id from the originating request/job.
       * @example 66b3b91d-7b52-4a4d-a71d-f2ea8db4a99c
       */
      readonly traceId: string;
    };
    readonly AdminUserAccountDeletionAuditsListEnvelopeDto: {
      readonly data: readonly components["schemas"]["AdminUserAccountDeletionAuditDto"][];
      readonly meta: components["schemas"]["CursorPaginationMetaDto"];
    };
    readonly AdminUserDto: {
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly createdAt: string;
      /** @example user@example.com */
      readonly email: string;
      /** @example false */
      readonly emailVerified: boolean;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
      /**
       * @example [
       *       "USER"
       *     ]
       */
      readonly roles: readonly string[];
      /**
       * @example ACTIVE
       * @enum {string}
       */
      readonly status: "ACTIVE" | "SUSPENDED" | "DELETED";
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly suspendedAt?: string | null;
      /**
       * @description Internal-only admin note for why the user is suspended.
       * @example Abuse detected
       */
      readonly suspendedReason?: string | null;
    };
    readonly AdminUserEnvelopeDto: {
      readonly data: components["schemas"]["AdminUserDto"];
    };
    readonly AdminUserRoleChangeAuditDto: {
      /** @example c1b6c1f7-5b2f-4e53-b33b-5af7f63a8c40 */
      readonly actorSessionId: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly actorUserId: string;
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly createdAt: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
      /**
       * @example ADMIN
       * @enum {string}
       */
      readonly newRole: "USER" | "ADMIN";
      /**
       * @example USER
       * @enum {string}
       */
      readonly oldRole: "USER" | "ADMIN";
      /** @example 9d8c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly targetUserId: string;
      /**
       * @description Equals X-Request-Id from the role change request.
       * @example 66b3b91d-7b52-4a4d-a71d-f2ea8db4a99c
       */
      readonly traceId: string;
    };
    readonly AdminUserRoleChangeAuditsListEnvelopeDto: {
      readonly data: readonly components["schemas"]["AdminUserRoleChangeAuditDto"][];
      readonly meta: components["schemas"]["CursorPaginationMetaDto"];
    };
    readonly AdminUsersListEnvelopeDto: {
      readonly data: readonly components["schemas"]["AdminUserDto"][];
      readonly meta: components["schemas"]["CursorPaginationMetaDto"];
    };
    readonly AdminWhoamiDto: {
      /** @example false */
      readonly emailVerified: boolean;
      /**
       * @example [
       *       "ADMIN"
       *     ]
       */
      readonly roles: readonly string[];
      /** @example c1b6c1f7-5b2f-4e53-b33b-5af7f63a8c40 */
      readonly sessionId: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly userId: string;
    };
    readonly AdminWhoamiEnvelopeDto: {
      readonly data: components["schemas"]["AdminWhoamiDto"];
    };
    readonly AuthResultDto: {
      /** @example <access-token> */
      readonly accessToken: string;
      /** @example <refresh-token> */
      readonly refreshToken: string;
      readonly user: components["schemas"]["AuthUserDto"];
    };
    readonly AuthResultEnvelopeDto: {
      readonly data: components["schemas"]["AuthResultDto"];
    };
    readonly AuthResultWithMeDto: {
      /** @example <access-token> */
      readonly accessToken: string;
      /** @example <refresh-token> */
      readonly refreshToken: string;
      readonly user: components["schemas"]["MeDto"];
    };
    readonly AuthResultWithMeEnvelopeDto: {
      readonly data: components["schemas"]["AuthResultWithMeDto"];
    };
    readonly AuthUserDto: {
      /**
       * @description Linked authentication methods on this account. Omitted on token refresh responses.
       * @example [
       *       "PASSWORD",
       *       "GOOGLE"
       *     ]
       */
      readonly authMethods?: readonly ("PASSWORD" | "GOOGLE")[];
      /** @example user@example.com */
      readonly email: string;
      /** @example false */
      readonly emailVerified: boolean;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
    };
    readonly ChangePasswordRequestDto: {
      readonly currentPassword: string;
      readonly newPassword: string;
    };
    readonly CompleteProfileImageUploadRequestDto: {
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly fileId: string;
    };
    readonly CreateProfileImageUploadRequestDto: {
      /**
       * @description Declared MIME type for the upload. Must match the Content-Type used during upload.
       * @example image/webp
       * @enum {string}
       */
      readonly contentType: "image/jpeg" | "image/png" | "image/webp";
      /**
       * @description Declared size of the upload in bytes (used to verify the stored object).
       * @example 123456
       */
      readonly sizeBytes: number;
    };
    readonly CursorPaginationMetaDto: {
      /** @example true */
      readonly hasMore: boolean;
      /** @example 25 */
      readonly limit: number;
      /** @example eyJ2IjoxLCJzb3J0IjoiLWNyZWF0ZWRBdCIsImFmdGVyIjp7fX0 */
      readonly nextCursor?: string;
    };
    readonly LogoutRequestDto: {
      /** @example <refresh-token> */
      readonly refreshToken: string;
    };
    readonly MeDto: {
      /** @description When set, the account is scheduled for deletion. The request can be canceled until scheduledFor. */
      readonly accountDeletion?:
        components["schemas"]["AccountDeletionDto"] | null;
      /**
       * @description Linked authentication methods on this account.
       * @example [
       *       "PASSWORD"
       *     ]
       */
      readonly authMethods: readonly ("PASSWORD" | "GOOGLE")[];
      /** @example user@example.com */
      readonly email: string;
      /** @example false */
      readonly emailVerified: boolean;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
      readonly profile: components["schemas"]["MeProfileDto"];
      /**
       * @example [
       *       "USER"
       *     ]
       */
      readonly roles: readonly string[];
    };
    readonly MeEnvelopeDto: {
      readonly data: components["schemas"]["MeDto"];
    };
    readonly MeProfileDto: {
      /** @example Dante */
      readonly displayName?: string | null;
      /** @example Alighieri */
      readonly familyName?: string | null;
      /** @example Dante */
      readonly givenName?: string | null;
      /**
       * @description Current profile image stored file ID. Use `GET /v1/me/profile-image/url` to get a short-lived URL for rendering.
       * @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0
       */
      readonly profileImageFileId?: string | null;
    };
    readonly MePushTokenUpsertRequestDto: {
      /**
       * @description Client platform where the push token was minted.
       * @example ANDROID
       * @enum {string}
       */
      readonly platform: "ANDROID" | "IOS" | "WEB";
      /**
       * @description FCM registration token for this device/app install.
       * @example <fcm-registration-token>
       */
      readonly token: string;
    };
    readonly MeSessionDto: {
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly createdAt: string;
      /** @example true */
      readonly current: boolean;
      /** @example device-a */
      readonly deviceId?: string | null;
      /** @example iPhone 15 */
      readonly deviceName?: string | null;
      /**
       * Format: date-time
       * @example 2026-02-10T12:34:56.789Z
       */
      readonly expiresAt: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly id: string;
      /** @example 203.0.113.10 */
      readonly ip?: string | null;
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly lastSeenAt: string;
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly revokedAt?: string | null;
      /**
       * @example active
       * @enum {string}
       */
      readonly status: "active" | "revoked" | "expired";
      /** @example Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 */
      readonly userAgent?: string | null;
    };
    readonly MeSessionsListEnvelopeDto: {
      readonly data: readonly components["schemas"]["MeSessionDto"][];
      readonly meta: components["schemas"]["CursorPaginationMetaDto"];
    };
    readonly OidcConnectRequestDto: {
      /** @example <oidc-id-token> */
      readonly idToken: string;
      /**
       * @example GOOGLE
       * @enum {string}
       */
      readonly provider: "GOOGLE";
    };
    readonly OidcExchangeRequestDto: {
      /** @description Stable per-device identifier (recommended). */
      readonly deviceId?: string;
      /** @description Human-friendly device name (optional). */
      readonly deviceName?: string;
      /** @example <oidc-id-token> */
      readonly idToken: string;
      /**
       * @example GOOGLE
       * @enum {string}
       */
      readonly provider: "GOOGLE";
    };
    readonly PasswordLoginRequestDto: {
      /** @description Stable per-device identifier (recommended). */
      readonly deviceId?: string;
      /** @description Human-friendly device name (optional). */
      readonly deviceName?: string;
      /** @example user@example.com */
      readonly email: string;
      readonly password: string;
    };
    readonly PasswordRegisterRequestDto: {
      /** @description Stable per-device identifier (recommended). */
      readonly deviceId?: string;
      /** @description Human-friendly device name (optional). */
      readonly deviceName?: string;
      /** @example user@example.com */
      readonly email: string;
      readonly password: string;
    };
    readonly PasswordResetConfirmRequestDto: {
      readonly newPassword: string;
      /** @example <password-reset-token> */
      readonly token: string;
    };
    readonly PasswordResetRequestDto: {
      /** @example user@example.com */
      readonly email: string;
    };
    readonly PatchMeProfileDto: {
      /** @example Dante */
      readonly displayName?: string | null;
      /** @example Alighieri */
      readonly familyName?: string | null;
      /** @example Dante */
      readonly givenName?: string | null;
    };
    readonly PatchMeRequestDto: {
      readonly profile: components["schemas"]["PatchMeProfileDto"];
    };
    readonly PresignedUploadDto: {
      /**
       * @description Headers that must be sent with the upload request.
       * @example {
       *       "Content-Type": "image/webp"
       *     }
       */
      readonly headers: {
        readonly [key: string]: string;
      };
      /**
       * @example PUT
       * @enum {string}
       */
      readonly method: "PUT";
      /** @example https://<r2-presigned-url> */
      readonly url: string;
    };
    readonly ProfileImageUploadPlanDto: {
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly expiresAt: string;
      /** @example 3d2c7b2a-2dd6-46a5-8f8e-3b5de8a5b0f0 */
      readonly fileId: string;
      readonly upload: components["schemas"]["PresignedUploadDto"];
    };
    readonly ProfileImageUploadPlanEnvelopeDto: {
      readonly data: components["schemas"]["ProfileImageUploadPlanDto"];
    };
    readonly ProfileImageUrlDto: {
      /**
       * Format: date-time
       * @example 2026-01-10T12:34:56.789Z
       */
      readonly expiresAt: string;
      /** @example https://<r2-presigned-url> */
      readonly url: string;
    };
    readonly ProfileImageUrlEnvelopeDto: {
      readonly data: components["schemas"]["ProfileImageUrlDto"];
    };
    readonly RefreshRequestDto: {
      /** @example <refresh-token> */
      readonly refreshToken: string;
    };
    readonly SetAdminUserRoleRequestDto: {
      /**
       * @example USER
       * @enum {string}
       */
      readonly role: "USER" | "ADMIN";
    };
    readonly SetAdminUserStatusRequestDto: {
      /**
       * @description Internal-only admin note for why the user is suspended.
       * @example Abuse detected
       */
      readonly reason?: string | null;
      /**
       * @example SUSPENDED
       * @enum {string}
       */
      readonly status: "ACTIVE" | "SUSPENDED";
    };
    readonly VerifyEmailRequestDto: {
      /** @example <verification-token> */
      readonly token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  readonly "auth.jwks.get": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": {
            readonly keys: readonly Record<string, never>[];
          };
        };
      };
    };
  };
  readonly "health.get": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Liveness check. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": {
            /** @example ok */
            readonly status: string;
          };
        };
      };
    };
  };
  readonly "ready.get": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description Readiness check. */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": {
            /** @example ok */
            readonly status: string;
          };
        };
      };
    };
  };
  readonly "admin.audit.userAccountDeletions.list": {
    readonly parameters: {
      readonly query?: {
        /** @description Opaque cursor from the previous response meta.nextCursor. */
        readonly cursor?: string;
        readonly "filter[action]"?:
          | "REQUESTED"
          | "CANCELED"
          | "FINALIZED"
          | "FINALIZE_BLOCKED_LAST_ADMIN";
        /** @description Comma-separated list (no repeated params). */
        readonly "filter[action][in]"?: string;
        readonly "filter[actorUserId]"?: string;
        readonly "filter[createdAt][gte]"?: string;
        readonly "filter[createdAt][lte]"?: string;
        readonly "filter[targetUserId]"?: string;
        readonly "filter[traceId]"?: string;
        /** @description Max results to return (default 25, max 250). */
        readonly limit?: number;
        /** @description Comma-separated fields; prefix "-" for descending. Max 3 fields. Default: "-createdAt". Allowed: createdAt, id */
        readonly sort?: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminUserAccountDeletionAuditsListEnvelopeDto"];
        };
      };
    };
  };
  readonly "admin.audit.userRoleChanges.list": {
    readonly parameters: {
      readonly query?: {
        /** @description Opaque cursor from the previous response meta.nextCursor. */
        readonly cursor?: string;
        readonly "filter[actorUserId]"?: string;
        readonly "filter[createdAt][gte]"?: string;
        readonly "filter[createdAt][lte]"?: string;
        readonly "filter[newRole]"?: "USER" | "ADMIN";
        /** @description Comma-separated list (no repeated params). */
        readonly "filter[newRole][in]"?: string;
        readonly "filter[oldRole]"?: "USER" | "ADMIN";
        /** @description Comma-separated list (no repeated params). */
        readonly "filter[oldRole][in]"?: string;
        readonly "filter[targetUserId]"?: string;
        readonly "filter[traceId]"?: string;
        /** @description Max results to return (default 25, max 250). */
        readonly limit?: number;
        /** @description Comma-separated fields; prefix "-" for descending. Max 3 fields. Default: "-createdAt". Allowed: createdAt, id */
        readonly sort?: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminUserRoleChangeAuditsListEnvelopeDto"];
        };
      };
    };
  };
  readonly "admin.users.list": {
    readonly parameters: {
      readonly query?: {
        /** @description Opaque cursor from the previous response meta.nextCursor. */
        readonly cursor?: string;
        readonly "filter[createdAt][gte]"?: string;
        readonly "filter[createdAt][lte]"?: string;
        readonly "filter[email]"?: string;
        readonly "filter[emailVerified]"?: boolean;
        readonly "filter[role]"?: "USER" | "ADMIN";
        /** @description Comma-separated list (no repeated params). */
        readonly "filter[role][in]"?: string;
        /** @description Max results to return (default 25, max 250). */
        readonly limit?: number;
        /** @description Free-text search query (endpoint-specific semantics). */
        readonly q?: string;
        /** @description Comma-separated fields; prefix "-" for descending. Max 3 fields. Default: "-createdAt". Allowed: createdAt, email, id */
        readonly sort?: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminUsersListEnvelopeDto"];
        };
      };
    };
  };
  readonly "admin.users.role.patch": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path: {
        readonly userId: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["SetAdminUserRoleRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminUserEnvelopeDto"];
        };
      };
    };
  };
  readonly "admin.users.status.patch": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path: {
        readonly userId: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["SetAdminUserStatusRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminUserEnvelopeDto"];
        };
      };
    };
  };
  readonly "admin.whoami.get": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AdminWhoamiEnvelopeDto"];
        };
      };
    };
  };
  readonly "auth.email.verification.resend": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.email.verify": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["VerifyEmailRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.logout": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["LogoutRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.oidc.connect": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["OidcConnectRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.oidc.exchange": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["OidcExchangeRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthResultWithMeEnvelopeDto"];
        };
      };
    };
  };
  readonly "auth.password.change": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["ChangePasswordRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.password.login": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordLoginRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthResultWithMeEnvelopeDto"];
        };
      };
    };
  };
  readonly "auth.password.register": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordRegisterRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthResultWithMeEnvelopeDto"];
        };
      };
    };
  };
  readonly "auth.password.reset.confirm": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordResetConfirmRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.password.reset.request": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PasswordResetRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "auth.refresh": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["RefreshRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["AuthResultEnvelopeDto"];
        };
      };
    };
  };
  readonly "users.me.get": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["MeEnvelopeDto"];
        };
      };
    };
  };
  readonly "users.me.patch": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["PatchMeRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["MeEnvelopeDto"];
        };
      };
    };
  };
  readonly "users.me.accountDeletion.cancel": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.accountDeletion.request": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.profileImage.clear": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.profileImage.complete": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CompleteProfileImageUploadRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.profileImage.upload": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: {
        /** @description Idempotency key for safe retries of write requests. Replays return `Idempotency-Replayed: true`. */
        readonly "Idempotency-Key"?: string;
      };
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["CreateProfileImageUploadRequestDto"];
      };
    };
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ProfileImageUploadPlanEnvelopeDto"];
        };
      };
    };
  };
  readonly "users.me.profileImage.url": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["ProfileImageUrlEnvelopeDto"];
        };
      };
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.pushToken.upsert": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly "application/json": components["schemas"]["MePushTokenUpsertRequestDto"];
      };
    };
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.pushToken.revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readonly "users.me.sessions.list": {
    readonly parameters: {
      readonly query?: {
        /** @description Opaque cursor from the previous response meta.nextCursor. */
        readonly cursor?: string;
        /** @description Max results to return (default 25, max 100). */
        readonly limit?: number;
        /** @description Comma-separated fields; prefix "-" for descending. Max 3 fields. Default: "-createdAt". Allowed: createdAt, id */
        readonly sort?: string;
      };
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly "application/json": components["schemas"]["MeSessionsListEnvelopeDto"];
        };
      };
    };
  };
  readonly "users.me.sessions.revoke": {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly sessionId: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
