/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Backend Core Kit API
 * Generated API contract (code-first).
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const passwordRegisterRequestDtoPasswordMin = 10;

export const PasswordRegisterRequestDto = zod.object({
  email: zod.string(),
  password: zod.string().min(passwordRegisterRequestDtoPasswordMin),
  deviceId: zod
    .string()
    .optional()
    .describe("Stable per-device identifier (recommended)."),
  deviceName: zod
    .string()
    .optional()
    .describe("Human-friendly device name (optional)."),
});

export type PasswordRegisterRequestDto = zod.input<
  typeof PasswordRegisterRequestDto
>;
export type PasswordRegisterRequestDtoOutput = zod.output<
  typeof PasswordRegisterRequestDto
>;

export const MeProfileDto = zod.object({
  profileImageFileId: zod
    .string()
    .nullish()
    .describe(
      "Current profile image stored file ID. Use `GET \/v1\/me\/profile-image\/url` to get a short-lived URL for rendering.",
    ),
  displayName: zod.string().nullish(),
  givenName: zod.string().nullish(),
  familyName: zod.string().nullish(),
});

export type MeProfileDto = zod.input<typeof MeProfileDto>;
export type MeProfileDtoOutput = zod.output<typeof MeProfileDto>;

export const AccountDeletionDto = zod.object({
  requestedAt: zod.iso.datetime({ offset: true }),
  scheduledFor: zod.iso.datetime({ offset: true }),
});

export type AccountDeletionDto = zod.input<typeof AccountDeletionDto>;
export type AccountDeletionDtoOutput = zod.output<typeof AccountDeletionDto>;

export const MeDto = zod.object({
  id: zod.string(),
  email: zod.string(),
  emailVerified: zod.boolean(),
  roles: zod.array(zod.string()),
  authMethods: zod
    .array(zod.enum(["PASSWORD", "GOOGLE"]))
    .describe("Linked authentication methods on this account."),
  profile: MeProfileDto,
  accountDeletion: AccountDeletionDto.nullish().describe(
    "When set, the account is scheduled for deletion. The request can be canceled until scheduledFor.",
  ),
});

export type MeDto = zod.input<typeof MeDto>;
export type MeDtoOutput = zod.output<typeof MeDto>;

export const AuthResultWithMeDto = zod.object({
  user: MeDto,
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export type AuthResultWithMeDto = zod.input<typeof AuthResultWithMeDto>;
export type AuthResultWithMeDtoOutput = zod.output<typeof AuthResultWithMeDto>;

export const AuthResultWithMeEnvelopeDto = zod.object({
  data: AuthResultWithMeDto,
});

export type AuthResultWithMeEnvelopeDto = zod.input<
  typeof AuthResultWithMeEnvelopeDto
>;
export type AuthResultWithMeEnvelopeDtoOutput = zod.output<
  typeof AuthResultWithMeEnvelopeDto
>;

export const OidcExchangeRequestDto = zod.object({
  provider: zod.enum(["GOOGLE"]),
  idToken: zod.string(),
  deviceId: zod
    .string()
    .optional()
    .describe("Stable per-device identifier (recommended)."),
  deviceName: zod
    .string()
    .optional()
    .describe("Human-friendly device name (optional)."),
});

export type OidcExchangeRequestDto = zod.input<typeof OidcExchangeRequestDto>;
export type OidcExchangeRequestDtoOutput = zod.output<
  typeof OidcExchangeRequestDto
>;

export const OidcConnectRequestDto = zod.object({
  provider: zod.enum(["GOOGLE"]),
  idToken: zod.string(),
});

export type OidcConnectRequestDto = zod.input<typeof OidcConnectRequestDto>;
export type OidcConnectRequestDtoOutput = zod.output<
  typeof OidcConnectRequestDto
>;

export const VerifyEmailRequestDto = zod.object({
  token: zod.string(),
});

export type VerifyEmailRequestDto = zod.input<typeof VerifyEmailRequestDto>;
export type VerifyEmailRequestDtoOutput = zod.output<
  typeof VerifyEmailRequestDto
>;

export const PasswordResetRequestDto = zod.object({
  email: zod.string(),
});

export type PasswordResetRequestDto = zod.input<typeof PasswordResetRequestDto>;
export type PasswordResetRequestDtoOutput = zod.output<
  typeof PasswordResetRequestDto
>;

export const passwordResetConfirmRequestDtoNewPasswordMin = 10;

export const PasswordResetConfirmRequestDto = zod.object({
  token: zod.string(),
  newPassword: zod.string().min(passwordResetConfirmRequestDtoNewPasswordMin),
});

export type PasswordResetConfirmRequestDto = zod.input<
  typeof PasswordResetConfirmRequestDto
>;
export type PasswordResetConfirmRequestDtoOutput = zod.output<
  typeof PasswordResetConfirmRequestDto
>;

export const PasswordLoginRequestDto = zod.object({
  email: zod.string(),
  password: zod.string().min(1),
  deviceId: zod
    .string()
    .optional()
    .describe("Stable per-device identifier (recommended)."),
  deviceName: zod
    .string()
    .optional()
    .describe("Human-friendly device name (optional)."),
});

export type PasswordLoginRequestDto = zod.input<typeof PasswordLoginRequestDto>;
export type PasswordLoginRequestDtoOutput = zod.output<
  typeof PasswordLoginRequestDto
>;

export const changePasswordRequestDtoNewPasswordMin = 10;

export const ChangePasswordRequestDto = zod.object({
  currentPassword: zod.string().min(1),
  newPassword: zod.string().min(changePasswordRequestDtoNewPasswordMin),
});

export type ChangePasswordRequestDto = zod.input<
  typeof ChangePasswordRequestDto
>;
export type ChangePasswordRequestDtoOutput = zod.output<
  typeof ChangePasswordRequestDto
>;

export const RefreshRequestDto = zod.object({
  refreshToken: zod.string(),
});

export type RefreshRequestDto = zod.input<typeof RefreshRequestDto>;
export type RefreshRequestDtoOutput = zod.output<typeof RefreshRequestDto>;

export const AuthUserDto = zod.object({
  id: zod.string(),
  email: zod.string(),
  emailVerified: zod.boolean(),
  authMethods: zod
    .array(zod.enum(["PASSWORD", "GOOGLE"]))
    .optional()
    .describe(
      "Linked authentication methods on this account. Omitted on token refresh responses.",
    ),
});

export type AuthUserDto = zod.input<typeof AuthUserDto>;
export type AuthUserDtoOutput = zod.output<typeof AuthUserDto>;

export const AuthResultDto = zod.object({
  user: AuthUserDto,
  accessToken: zod.string(),
  refreshToken: zod.string(),
});

export type AuthResultDto = zod.input<typeof AuthResultDto>;
export type AuthResultDtoOutput = zod.output<typeof AuthResultDto>;

export const AuthResultEnvelopeDto = zod.object({
  data: AuthResultDto,
});

export type AuthResultEnvelopeDto = zod.input<typeof AuthResultEnvelopeDto>;
export type AuthResultEnvelopeDtoOutput = zod.output<
  typeof AuthResultEnvelopeDto
>;

export const LogoutRequestDto = zod.object({
  refreshToken: zod.string(),
});

export type LogoutRequestDto = zod.input<typeof LogoutRequestDto>;
export type LogoutRequestDtoOutput = zod.output<typeof LogoutRequestDto>;

export const meSessionDtoUserAgentMax = 512;

export const MeSessionDto = zod.object({
  id: zod.string(),
  deviceId: zod.string().nullish(),
  deviceName: zod.string().nullish(),
  ip: zod.string().nullish(),
  userAgent: zod.string().max(meSessionDtoUserAgentMax).nullish(),
  lastSeenAt: zod.iso.datetime({ offset: true }),
  createdAt: zod.iso.datetime({ offset: true }),
  expiresAt: zod.iso.datetime({ offset: true }),
  revokedAt: zod.iso.datetime({ offset: true }).nullish(),
  current: zod.boolean(),
  status: zod.enum(["active", "revoked", "expired"]),
});

export type MeSessionDto = zod.input<typeof MeSessionDto>;
export type MeSessionDtoOutput = zod.output<typeof MeSessionDto>;

export const CursorPaginationMetaDto = zod.object({
  limit: zod.number(),
  hasMore: zod.boolean(),
  nextCursor: zod.string().optional(),
});

export type CursorPaginationMetaDto = zod.input<typeof CursorPaginationMetaDto>;
export type CursorPaginationMetaDtoOutput = zod.output<
  typeof CursorPaginationMetaDto
>;

export const MeSessionsListEnvelopeDto = zod.object({
  data: zod.array(MeSessionDto),
  meta: CursorPaginationMetaDto,
});

export type MeSessionsListEnvelopeDto = zod.input<
  typeof MeSessionsListEnvelopeDto
>;
export type MeSessionsListEnvelopeDtoOutput = zod.output<
  typeof MeSessionsListEnvelopeDto
>;

export const mePushTokenUpsertRequestDtoTokenMax = 2048;

export const MePushTokenUpsertRequestDto = zod.object({
  platform: zod
    .enum(["ANDROID", "IOS", "WEB"])
    .describe("Client platform where the push token was minted."),
  token: zod
    .string()
    .max(mePushTokenUpsertRequestDtoTokenMax)
    .describe("FCM registration token for this device\/app install."),
});

export type MePushTokenUpsertRequestDto = zod.input<
  typeof MePushTokenUpsertRequestDto
>;
export type MePushTokenUpsertRequestDtoOutput = zod.output<
  typeof MePushTokenUpsertRequestDto
>;

export const MeEnvelopeDto = zod.object({
  data: MeDto,
});

export type MeEnvelopeDto = zod.input<typeof MeEnvelopeDto>;
export type MeEnvelopeDtoOutput = zod.output<typeof MeEnvelopeDto>;

export const patchMeProfileDtoDisplayNameMax = 100;

export const patchMeProfileDtoGivenNameMax = 100;

export const patchMeProfileDtoFamilyNameMax = 100;

export const PatchMeProfileDto = zod.object({
  displayName: zod
    .string()
    .min(1)
    .max(patchMeProfileDtoDisplayNameMax)
    .nullish(),
  givenName: zod.string().min(1).max(patchMeProfileDtoGivenNameMax).nullish(),
  familyName: zod.string().min(1).max(patchMeProfileDtoFamilyNameMax).nullish(),
});

export type PatchMeProfileDto = zod.input<typeof PatchMeProfileDto>;
export type PatchMeProfileDtoOutput = zod.output<typeof PatchMeProfileDto>;

export const PatchMeRequestDto = zod.object({
  profile: PatchMeProfileDto,
});

export type PatchMeRequestDto = zod.input<typeof PatchMeRequestDto>;
export type PatchMeRequestDtoOutput = zod.output<typeof PatchMeRequestDto>;

export const createProfileImageUploadRequestDtoSizeBytesMax = 5000000;

export const CreateProfileImageUploadRequestDto = zod.object({
  contentType: zod
    .enum(["image/jpeg", "image/png", "image/webp"])
    .describe(
      "Declared MIME type for the upload. Must match the Content-Type used during upload.",
    ),
  sizeBytes: zod
    .number()
    .min(1)
    .max(createProfileImageUploadRequestDtoSizeBytesMax)
    .describe(
      "Declared size of the upload in bytes (used to verify the stored object).",
    ),
});

export type CreateProfileImageUploadRequestDto = zod.input<
  typeof CreateProfileImageUploadRequestDto
>;
export type CreateProfileImageUploadRequestDtoOutput = zod.output<
  typeof CreateProfileImageUploadRequestDto
>;

export const PresignedUploadDto = zod.object({
  method: zod.enum(["PUT"]),
  url: zod.string(),
  headers: zod
    .looseObject({})
    .describe("Headers that must be sent with the upload request."),
});

export type PresignedUploadDto = zod.input<typeof PresignedUploadDto>;
export type PresignedUploadDtoOutput = zod.output<typeof PresignedUploadDto>;

export const ProfileImageUploadPlanDto = zod.object({
  fileId: zod.string(),
  upload: PresignedUploadDto,
  expiresAt: zod.iso.datetime({ offset: true }),
});

export type ProfileImageUploadPlanDto = zod.input<
  typeof ProfileImageUploadPlanDto
>;
export type ProfileImageUploadPlanDtoOutput = zod.output<
  typeof ProfileImageUploadPlanDto
>;

export const ProfileImageUploadPlanEnvelopeDto = zod.object({
  data: ProfileImageUploadPlanDto,
});

export type ProfileImageUploadPlanEnvelopeDto = zod.input<
  typeof ProfileImageUploadPlanEnvelopeDto
>;
export type ProfileImageUploadPlanEnvelopeDtoOutput = zod.output<
  typeof ProfileImageUploadPlanEnvelopeDto
>;

export const CompleteProfileImageUploadRequestDto = zod.object({
  fileId: zod.string(),
});

export type CompleteProfileImageUploadRequestDto = zod.input<
  typeof CompleteProfileImageUploadRequestDto
>;
export type CompleteProfileImageUploadRequestDtoOutput = zod.output<
  typeof CompleteProfileImageUploadRequestDto
>;

export const ProfileImageUrlDto = zod.object({
  url: zod.string(),
  expiresAt: zod.iso.datetime({ offset: true }),
});

export type ProfileImageUrlDto = zod.input<typeof ProfileImageUrlDto>;
export type ProfileImageUrlDtoOutput = zod.output<typeof ProfileImageUrlDto>;

export const ProfileImageUrlEnvelopeDto = zod.object({
  data: ProfileImageUrlDto,
});

export type ProfileImageUrlEnvelopeDto = zod.input<
  typeof ProfileImageUrlEnvelopeDto
>;
export type ProfileImageUrlEnvelopeDtoOutput = zod.output<
  typeof ProfileImageUrlEnvelopeDto
>;

export const AdminWhoamiDto = zod.object({
  userId: zod.string(),
  sessionId: zod.string(),
  emailVerified: zod.boolean(),
  roles: zod.array(zod.string()),
});

export type AdminWhoamiDto = zod.input<typeof AdminWhoamiDto>;
export type AdminWhoamiDtoOutput = zod.output<typeof AdminWhoamiDto>;

export const AdminWhoamiEnvelopeDto = zod.object({
  data: AdminWhoamiDto,
});

export type AdminWhoamiEnvelopeDto = zod.input<typeof AdminWhoamiEnvelopeDto>;
export type AdminWhoamiEnvelopeDtoOutput = zod.output<
  typeof AdminWhoamiEnvelopeDto
>;

export const AdminUserDto = zod.object({
  id: zod.string(),
  email: zod.string(),
  emailVerified: zod.boolean(),
  roles: zod.array(zod.string()),
  status: zod.enum(["ACTIVE", "SUSPENDED", "DELETED"]),
  suspendedAt: zod.iso.datetime({ offset: true }).nullish(),
  suspendedReason: zod
    .string()
    .nullish()
    .describe("Internal-only admin note for why the user is suspended."),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type AdminUserDto = zod.input<typeof AdminUserDto>;
export type AdminUserDtoOutput = zod.output<typeof AdminUserDto>;

export const AdminUsersListEnvelopeDto = zod.object({
  data: zod.array(AdminUserDto),
  meta: CursorPaginationMetaDto,
});

export type AdminUsersListEnvelopeDto = zod.input<
  typeof AdminUsersListEnvelopeDto
>;
export type AdminUsersListEnvelopeDtoOutput = zod.output<
  typeof AdminUsersListEnvelopeDto
>;

export const SetAdminUserRoleRequestDto = zod.object({
  role: zod.enum(["USER", "ADMIN"]),
});

export type SetAdminUserRoleRequestDto = zod.input<
  typeof SetAdminUserRoleRequestDto
>;
export type SetAdminUserRoleRequestDtoOutput = zod.output<
  typeof SetAdminUserRoleRequestDto
>;

export const AdminUserEnvelopeDto = zod.object({
  data: AdminUserDto,
});

export type AdminUserEnvelopeDto = zod.input<typeof AdminUserEnvelopeDto>;
export type AdminUserEnvelopeDtoOutput = zod.output<
  typeof AdminUserEnvelopeDto
>;

export const SetAdminUserStatusRequestDto = zod.object({
  status: zod.enum(["ACTIVE", "SUSPENDED"]),
  reason: zod
    .string()
    .nullish()
    .describe("Internal-only admin note for why the user is suspended."),
});

export type SetAdminUserStatusRequestDto = zod.input<
  typeof SetAdminUserStatusRequestDto
>;
export type SetAdminUserStatusRequestDtoOutput = zod.output<
  typeof SetAdminUserStatusRequestDto
>;

export const AdminUserRoleChangeAuditDto = zod.object({
  id: zod.string(),
  actorUserId: zod.string(),
  actorSessionId: zod.string(),
  targetUserId: zod.string(),
  oldRole: zod.enum(["USER", "ADMIN"]),
  newRole: zod.enum(["USER", "ADMIN"]),
  traceId: zod
    .string()
    .describe("Equals X-Request-Id from the role change request."),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type AdminUserRoleChangeAuditDto = zod.input<
  typeof AdminUserRoleChangeAuditDto
>;
export type AdminUserRoleChangeAuditDtoOutput = zod.output<
  typeof AdminUserRoleChangeAuditDto
>;

export const AdminUserRoleChangeAuditsListEnvelopeDto = zod.object({
  data: zod.array(AdminUserRoleChangeAuditDto),
  meta: CursorPaginationMetaDto,
});

export type AdminUserRoleChangeAuditsListEnvelopeDto = zod.input<
  typeof AdminUserRoleChangeAuditsListEnvelopeDto
>;
export type AdminUserRoleChangeAuditsListEnvelopeDtoOutput = zod.output<
  typeof AdminUserRoleChangeAuditsListEnvelopeDto
>;

export const AdminUserAccountDeletionAuditDto = zod.object({
  id: zod.string(),
  actorUserId: zod.string(),
  actorSessionId: zod.string(),
  targetUserId: zod.string(),
  action: zod.enum([
    "REQUESTED",
    "CANCELED",
    "FINALIZED",
    "FINALIZE_BLOCKED_LAST_ADMIN",
  ]),
  traceId: zod
    .string()
    .describe("Equals X-Request-Id from the originating request\/job."),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type AdminUserAccountDeletionAuditDto = zod.input<
  typeof AdminUserAccountDeletionAuditDto
>;
export type AdminUserAccountDeletionAuditDtoOutput = zod.output<
  typeof AdminUserAccountDeletionAuditDto
>;

export const AdminUserAccountDeletionAuditsListEnvelopeDto = zod.object({
  data: zod.array(AdminUserAccountDeletionAuditDto),
  meta: CursorPaginationMetaDto,
});

export type AdminUserAccountDeletionAuditsListEnvelopeDto = zod.input<
  typeof AdminUserAccountDeletionAuditsListEnvelopeDto
>;
export type AdminUserAccountDeletionAuditsListEnvelopeDtoOutput = zod.output<
  typeof AdminUserAccountDeletionAuditsListEnvelopeDto
>;
/**
 * Indicates whether the process is alive.
 * @summary Liveness check
 */
export const HealthGetResponse = zod.object({
  status: zod.string(),
});

/**
 * Indicates whether the service is ready to receive traffic.
 * @summary Readiness check
 */
export const ReadyGetResponse = zod.object({
  status: zod.string(),
});

/**
 * Creates a user and immediately issues first-party access + refresh tokens.
 * @summary Register (password)
 */
export const AuthPasswordRegisterResponse = AuthResultWithMeEnvelopeDto;

/**
 * Verifies an OIDC id_token (e.g., Google) and issues first-party access + refresh tokens. Does not auto-link to an existing password account purely by email.
 * @summary Exchange OIDC id_token
 */
export const AuthOidcExchangeResponse = AuthResultWithMeEnvelopeDto;

/**
 * Links an OIDC identity (e.g., Google) to the authenticated user. If the OIDC email matches the user email, the user email is marked verified.
 * @summary Connect OIDC identity (current user)
 */
export const AuthOidcConnectResponse = zod.void();

/**
 * Verifies a user email using a token sent via email.
 * @summary Verify email
 */
export const AuthEmailVerifyResponse = zod.void();

/**
 * Enqueues a new verification email for the authenticated user (rate limited).
 * @summary Resend verification email (current user)
 */
export const AuthEmailVerificationResendResponse = zod.void();

/**
 * Enqueues a password reset email for an existing user. Returns 204 even if the email is unknown to avoid account enumeration.
 * @summary Request password reset
 */
export const AuthPasswordResetRequestResponse = zod.void();

/**
 * Resets the user password using a one-time token and revokes all sessions.
 * @summary Confirm password reset
 */
export const AuthPasswordResetConfirmResponse = zod.void();

/**
 * Authenticates a user and issues first-party access + refresh tokens.
 * @summary Login (password)
 */
export const AuthPasswordLoginResponse = AuthResultWithMeEnvelopeDto;

/**
 * Changes the authenticated user password. Revokes other sessions (and their refresh tokens) but keeps the current session active.
 * @summary Change password (current user)
 */
export const AuthPasswordChangeResponse = zod.void();

/**
 * Rotates the refresh token and returns a new access + refresh token.
 * @summary Refresh tokens
 */
export const AuthRefreshResponse = AuthResultEnvelopeDto;

/**
 * Revokes the session associated with the provided refresh token.
 * @summary Logout
 */
export const AuthLogoutResponse = zod.void();

/**
 * Publishes public keys used to verify access tokens.
 * @summary JWKS
 */
export const AuthJwksGetResponse = zod.object({
  keys: zod.array(zod.looseObject({})),
});

/**
 * Lists all sessions (active, revoked, expired) for the authenticated user. Revoked sessions have refresh tokens revoked; access tokens remain valid until expiry.
 * @summary List current user sessions
 */
export const UsersMeSessionsListResponse = MeSessionsListEnvelopeDto;

/**
 * Revokes the given session and its refresh tokens. Idempotent.
 * @summary Revoke a session (current user)
 */
export const UsersMeSessionsRevokeResponse = zod.void();

/**
 * Stores the FCM registration token for the current session. Idempotent; replaces any existing token for the session.
 * @summary Register/update push token (current session)
 */
export const UsersMePushTokenUpsertResponse = zod.void();

/**
 * Clears the stored push token for the current session. Idempotent.
 * @summary Revoke push token (current session)
 */
export const UsersMePushTokenRevokeResponse = zod.void();

/**
 * Returns the authenticated user profile.
 * @summary Get current user
 */
export const UsersMeGetResponse = MeEnvelopeDto;

/**
 * Partially updates the authenticated user profile. Omitted fields are unchanged; null clears a field.
 * @summary Update current user profile
 */
export const UsersMePatchResponse = MeEnvelopeDto;

/**
 * Creates an upload record and returns a short-lived presigned URL for direct upload to object storage.
 * @summary Create a profile image upload plan (presigned URL)
 */
export const UsersMeProfileImageUploadResponse =
  ProfileImageUploadPlanEnvelopeDto;

/**
 * Verifies the uploaded object and attaches it to the current user profile.
 * @summary Finalize a profile image upload
 */
export const UsersMeProfileImageCompleteResponse = zod.void();

/**
 * Detaches the current profile image (if any) and marks the stored file deleted. Object storage deletion is best-effort.
 * @summary Clear current profile image
 */
export const UsersMeProfileImageClearResponse = zod.void();

/**
 * Returns a short-lived presigned URL for rendering the current profile image. Returns 204 when no profile image is set.
 * @summary Get current profile image URL
 */
export const UsersMeProfileImageUrlResponse = ProfileImageUrlEnvelopeDto;

/**
 * Schedules account deletion 30 days in the future. The account remains usable during the grace period and the request can be canceled. After the grace period, the account is de-identified (PII erased) and the email becomes reusable.
 * @summary Request account deletion (30-day grace)
 */
export const UsersMeAccountDeletionRequestResponse = zod.void();

/**
 * Cancels a previously scheduled account deletion request.
 * @summary Cancel account deletion
 */
export const UsersMeAccountDeletionCancelResponse = zod.void();

/**
 * Returns the authenticated principal. For /v1/admin/* endpoints, roles are hydrated from the database to ensure immediate demotion/promotion.
 * @summary Get current principal (admin)
 */
export const AdminWhoamiGetResponse = AdminWhoamiEnvelopeDto;

/**
 * Admin-only user listing with cursor pagination, sorting, filtering, and search.
 * @summary List users
 */
export const AdminUsersListResponse = AdminUsersListEnvelopeDto;

/**
 * Sets the user role. For /v1/admin/* endpoints, RBAC roles are hydrated from the database on every request (promotion/demotion takes effect immediately).
 * @summary Set user role
 */
export const AdminUsersRolePatchResponse = AdminUserEnvelopeDto;

/**
 * Sets the user status (ACTIVE/SUSPENDED). Suspended users cannot refresh tokens and are blocked from /v1/admin/* endpoints immediately.
 * @summary Set user status
 */
export const AdminUsersStatusPatchResponse = AdminUserEnvelopeDto;

/**
 * Lists role change audit events. Filter by traceId to locate the exact change request.
 * @summary List user role changes
 */
export const AdminAuditUserRoleChangesListResponse =
  AdminUserRoleChangeAuditsListEnvelopeDto;

/**
 * Lists account deletion audit events (request/cancel/finalization). ID-only; filter by traceId to locate the originating request/job.
 * @summary List user account deletion events
 */
export const AdminAuditUserAccountDeletionsListResponse =
  AdminUserAccountDeletionAuditsListEnvelopeDto;
